steps:
  - label: 'validate packer template'
    command: 'docker build --no-cache . -t gusto/packer && docker run -v $(pwd):/packer -e vpc_id -e subnet_id gusto/packer make validate'
    agents:
      queue: 'eks-ubuntu-packer'
  - label: ':ubuntu: Test EKS ubuntu AMI for 1.16'
    command: 'docker build --no-cache . -t gusto/packer && docker run -v $(pwd):/packer -e vpc_id -e subnet_id gusto/packer make 1.16'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: '!master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Test EKS ubuntu AMI for 1.17'
    command: 'docker build --no-cache . -t gusto/packer && docker run -v $(pwd):/packer -e vpc_id -e subnet_id gusto/packer make 1.17'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: '!master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Test EKS ubuntu AMI for 1.18'
    command: 'docker build --no-cache . -t gusto/packer && docker run -v $(pwd):/packer -e vpc_id -e subnet_id gusto/packer make 1.18'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: '!master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Test EKS ubuntu AMI for 1.19'
    command: 'docker build --no-cache . -t gusto/packer && docker run -v $(pwd):/packer -e vpc_id -e subnet_id gusto/packer make 1.19'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: '!master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Test EKS ubuntu AMI latest'
    command: 'docker build --no-cache . -t gusto/packer && docker run -v $(pwd):/packer -e vpc_id -e subnet_id gusto/packer make latest'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: '!master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Publish ubuntu AMI 1.16'
    command: 'docker build --no-cache . -t gusto/packer && docker run -v $(pwd):/packer -e vpc_id -e subnet_id gusto/packer make publish-1.16'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: 'master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Publish ubuntu AMI 1.17'
    command: 'docker build --no-cache . -t gusto/packer && docker run -v $(pwd):/packer -e vpc_id -e subnet_id gusto/packer make publish-1.17'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: 'master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Publish ubuntu AMI 1.18'
    command: 'docker build --no-cache . -t gusto/packer && docker run -v $(pwd):/packer -e vpc_id -e subnet_id gusto/packer make publish-1.18'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: 'master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Publish ubuntu AMI 1.19'
    command: 'docker build --no-cache . -t gusto/packer && docker run -v $(pwd):/packer -e vpc_id -e subnet_id gusto/packer make publish-1.19'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: 'master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Publish ubuntu AMI latest'
    command: 'docker build --no-cache . -t gusto/packer && docker run -v $(pwd):/packer -e vpc_id -e subnet_id gusto/packer make publish-latest'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: 'master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
