steps:
  - label: 'validate packer template'
    command: 'docker build . -t gusto/packer && docker run -v $(pwd):/packer -e VPC_ID -e SUBNET_ID gusto/packer make validate'
    agents:
      queue: 'eks-ubuntu-packer'
  - label: ':ubuntu: Test EKS ubuntu AMI for 1.10'
    command: 'docker build . -t gusto/packer && docker run -v $(pwd):/packer -e VPC_ID -e SUBNET_ID gusto/packer make 1.10'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: '!master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Test EKS ubuntu AMI 1.11'
    command: 'docker build . -t gusto/packer && docker run -v $(pwd):/packer -e VPC_ID -e SUBNET_ID gusto/packer make 1.11'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: '!master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Test EKS ubuntu AMI 1.12'
    command: 'docker build . -t gusto/packer && docker run -v $(pwd):/packer -e VPC_ID -e SUBNET_ID gusto/packer make 1.12'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: '!master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Test EKS ubuntu AMI 1.12'
    command: 'docker build . -t gusto/packer && docker run -v $(pwd):/packer -e VPC_ID -e SUBNET_ID gusto/packer make latest'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: '!master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"

  - label: ':ubuntu: Publish ubuntu AMI 1.10'
    command: 'docker build . -t gusto/packer && docker run -v $(pwd):/packer -e VPC_ID -e SUBNET_ID gusto/packer make publish-1.10'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: 'master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Publish ubuntu AMI 1.11'
    command: 'docker build . -t gusto/packer && docker run -v $(pwd):/packer -e VPC_ID -e SUBNET_ID gusto/packer make publish-1.11'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: 'master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Publish ubuntu AMI 1.12'
    command: 'docker build . -t gusto/packer && docker run -v $(pwd):/packer -e VPC_ID -e SUBNET_ID gusto/packer make publish-1.12'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: 'master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
  - label: ':ubuntu: Publish ubuntu AMI 1.12'
    command: 'docker build . -t gusto/packer && docker run -v $(pwd):/packer -e VPC_ID -e SUBNET_ID gusto/packer make publish-latest'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: 'master'
    retry:
      automatic:
        - limit: 3
          exit_status: "*"
