steps:
  - label: 'validate packer template'
    command: 'docker build . -t gusto/packer && docker run -v $(pwd):/packer -e VPC_ID -e SUBNET_ID gusto/packer validate'
    agents:
      queue: 'eks-ubuntu-packer'
  - label: ':ubuntu: Publish ubuntu AMI 1.10'
    command: 'docker build . -t gusto/packer && docker run -v $(pwd):/packer -e VPC_ID -e SUBNET_ID gusto/packer 1.10'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: 'master'
  - label: ':ubuntu: Publish ubuntu AMI 1.11'
    command: 'docker build . -t gusto/packer && docker run -v $(pwd):/packer -e VPC_ID -e SUBNET_ID gusto/packer 1.11'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: 'master'
  - label: ':ubuntu: Publish ubuntu AMI 1.12'
    command: 'docker build . -t gusto/packer && docker run -v $(pwd):/packer -e VPC_ID -e SUBNET_ID gusto/packer 1.12'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: 'master'
  - label: ':ubuntu: Publish ubuntu AMI 1.12'
    command: 'docker build . -t gusto/packer && docker run -v $(pwd):/packer -e VPC_ID -e SUBNET_ID gusto/packer latest'
    agents:
      queue: 'eks-ubuntu-packer'
    branches: 'master'

